# this file is *NOT* reloaded automatically when use 'bundle exec jekyll serve'.
# If change this file, restart server process.

title: Hartgeld Studio
email: lorehartgeld@gmail.com
description: >
  Hartgeld · Form · Code · Type
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.holgerardelt.de/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hlgrrdlt
github_username:  hartgeld

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
    # style: compact
    load_paths:
      - _sass
      - node_modules/normalize-scss/sass
exclude: [vendor]
assets:
   sources:
     -assets/fonts
     -assets/javascript
     -assets/graphics
     -node_modules
