backend:
	name: git-gateway
	branch:master # Branch to update (defaults to master)

# enable Editorial Workflow – adds an interface for drafting, reviewing and approving posts.
publish_mode: editorial_workflow

# media files will bes stored in the repo in images/uploads
media_folder: "/images/uploads"
